name: Prepare Reth Image

on:
  workflow_call:
    inputs:
      image_tag:
        required: true
        type: string
        description: "Docker image tag to use (e.g. reth:local)"
      binary_name:
        required: false
        type: string
        default: "reth"
        description: "Binary name to build (reth or op-reth)"
      cargo_features:
        required: false
        type: string
        default: "asm-keccak"
        description: "Cargo features to enable"
      cargo_package:
        required: false
        type: string
        description: "Optional cargo package path"

jobs:
  prepare-reth:
    if: github.repository == 'Rimeeeeee/reth'
    timeout-minutes: 45
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - run: mkdir artifacts

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and export reth image to tarball
        uses: docker/build-push-action@v6
        with:
          context: .
          file: .github/assets/hive/Dockerfile
          tags: ${{ inputs.image_tag }}
          outputs: type=docker,dest=./artifacts/reth_image.tar
          build-args: |
            CARGO_BIN=${{ inputs.binary_name }}
            MANIFEST_PATH=${{ inputs.cargo_package }}
            FEATURES=${{ inputs.cargo_features }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Upload reth image tarball
        uses: actions/upload-artifact@v4
        with:
          name: reth-image
          path: ./artifacts/reth_image.tar